<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>0.0.0.0</AssemblyVersion>
  </PropertyGroup>

  <Target Name="CopyAppCoreToAssemblyAppDataBin" AfterTargets="Build">
    <Copy
      SourceFiles="$(TargetDir)App.Core.dll"
      DestinationFolder="../Assembly/AppData/bin"
      SkipUnchangedFiles="true"
      Condition="Exists('$(TargetDir)App.Core.dll')" />
  </Target>

</Project>
